language:
  - python
  - haskell
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
ghc:
  - 7.8
install:
  - pip install unittest-data-provider
  - sudo apt-get install haskell-platform cabal-install
  - cabal update
  - cabal install hspec
script:
  - python python/flask/TicTacTest.py
  - runhaskell haskell/TicTacTest.hs
notifications:
  email: false
